### ISSUE TITLE
Create Way(s) To report messages that are scams but have been missed

### ISSUE THREAD

**Issue by Bluesy1** [Bluesy1/ScamScanner#3]
Message Menu?
Slash Command?
Modal Input?

**Comment by Bluesy1** [comment]
Need input from others on the best way to do this
Not sure if one/multiple approaches would be better

**Comment by CasparN** [comment]
1. With a modal you could have more information but I think slash commands would be more convenient as you can copy/paste stuff more easily. 
2.  How you would keep track of the messages is up to you, a channel would be the handiest for you? seems nicer to look through than a text file.
3. Do add the way to blacklist people from doing this stuff, you will get spam. Automatically or manually.

**Comment by Bluesy1** [comment]
@CasparN a couple things to keep in mind:
Any report feature would be limited to admins, those with perms to manage the bot, and people with manage messages. W nobody couldn't report a message, that's unsafe.
A slash command could be done in such a way it either then brings up a modal or brings an ephemeral button that has a modal response.
With regards to storing messages, the developer T&S has to be considered

**Comment by CasparN** [comment]
I figured only admins could do this, but you've seen what some admins do so, it could still be spammy.

I'm not educated enough to comment on the rest.

**Comment by Bluesy1** [comment]
I think what i'm going to do for now (until i get access to modals, is give a few different options.
Message context option
and then application commands wise:
one for content, and one for a message link. i don't think there's another that i'm missing that i can do at the moment.
let me know if i am @CasparN

**Comment by Bluesy1** [comment]
Once i get access to modals i'll reopen this/make a new issue

**Comment by Bluesy1** [comment]
Closed by #12 through #23
