### ISSUE TITLE
Error on ``/config`` command when missing an optional argument.

### ISSUE THREAD

**Issue by CasparN** [Bluesy1/ScamScanner#37]
**Describe the bug**
Error on the use of command /config moderation, the error message is below.
> Something went wrong while running command config.Bluesy#8150 has been notified.

**To Reproduce**
Steps to reproduce the behaviour:
1. Use the command /config moderation
2. Fill the command in as usual but leave out ``update_log`` (optional)
3. Run the command
4. And there's the error

**Expected behaviour**
For the command to query my settings and show what would normally be shown when providing an ``update_log`` channel.

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Desktop application
 - Following are where the command was ran
 - Server ID: 909125279518191678
 - Channel ID: 909125280633847829

**Additional context**
Good luck fixing it

**Comment by Bluesy1** [comment]
RE: @CasparN 
Should just need a simple None if x is none type check.
