### ISSUE TITLE
Create a user generated/placeholder ban message

### ISSUE THREAD

**Issue by Bluesy1** [Bluesy1/ScamScanner#6]
This is needed in case of accidental bans

**Comment by CasparN** [comment]
I don't think it has to be user generated, but it could be. Just a: 

You've been automatically banned because of scam prevention, if you think this is false, please apply here. (form on your website linked to the dashboard)

**Comment by Bluesy1** [comment]
This *should* be mostly complete now.
just needs to be tested in prod, and then it should be complete

**Comment by Bluesy1** [comment]
In testing, seems to be working. closing for now
